{"files":[{"patch":"@@ -206,2 +206,2 @@\n-                    \/** @throws X sometimes *\/\n-                    public <X extends Throwable> void m() throws X { }\n+                    \/** @throws T sometimes *\/\n+                    public <T extends RuntimeException> void m() { }\n@@ -214,1 +214,1 @@\n-                    \/** @throws X {@inheritDoc} *\/\n+                    \/** @throws T {@inheritDoc} *\/\n@@ -222,2 +222,2 @@\n-        \/\/ Child.java:5: error: invalid use of @throws\n-        \/\/    \/** @throws X {@inheritDoc} *\/\n+        \/\/ Child.java:5: error: reference not found\n+        \/\/    \/** @throws T {@inheritDoc} *\/\n@@ -227,2 +227,0 @@\n-        \/\/ It just happens so that X is resolved to a package.\n-        \/\/ This should probably be fixed eventually. \/\/ TODO: add a link to the JBS issue\n@@ -230,2 +228,2 @@\n-                Child.java:5: warning: type found is not of exception type: X (MODULE <unnamed module> PACKAGE X)\n-                    \/** @throws X {@inheritDoc} *\/\n+                Child.java:5: warning: cannot find exception type by name\n+                    \/** @throws T {@inheritDoc} *\/\n","filename":"test\/langtools\/jdk\/javadoc\/doclet\/testThrowsInheritanceMatching\/TestExceptionTypeMatching.java","additions":7,"deletions":9,"binary":false,"changes":16,"status":"modified"}]}